import { Wallet } from "@/components/wallet";
import Head from "next/head";
import styles from "@/styles/home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome - Sérgio Damasceno</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Wallet />
      </div>
    </>
  );
}
